# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nr2_types.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'nr2_types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fnr2_types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n\rLevel3ExtData\x12\x10\n\x08\x44\x61taMask\x18\x01 \x01(\x05\x12\x11\n\tDataScale\x18\x02 \x01(\x05\x12\x12\n\nDataOffset\x18\x03 \x01(\x05\x12\x12\n\nToppedMask\x18\x04 \x01(\x05\"\xb1\x03\n\nRadarFrame\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0c\n\x04ICAO\x18\x02 \x01(\t\x12\x13\n\x0bProductName\x18\x03 \x01(\t\x12(\n\x04\x44\x61te\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03VCP\x18\x05 \x01(\x05\x12\x12\n\nTiltNumber\x18\x06 \x01(\x05\x12\x16\n\x0e\x45levationAngle\x18\x07 \x01(\x02\x12\x10\n\x08Latitude\x18\x08 \x01(\x02\x12\x11\n\tLongitude\x18\t \x01(\x02\x12\x19\n\x11StartAzimuthAngle\x18\n \x01(\x02\x12\x11\n\tGateCount\x18\x0b \x01(\x05\x12\x13\n\x0bRadialCount\x18\x0c \x01(\x05\x12\x13\n\x0bUpperCutoff\x18\r \x01(\x02\x12\x13\n\x0bLowerCutoff\x18\x0e \x01(\x02\x12\r\n\x05Gates\x18\x0f \x03(\x02\x12\x13\n\x0bProductCode\x18\x10 \x01(\x05\x12\x1b\n\x13\x43oneOfSilenceRadius\x18\x11 \x01(\x02\x12%\n\rLevel3ExtData\x18\x12 \x01(\x0b\x32\x0e.Level3ExtData\x12\x17\n\x0fNyquistVelocity\x18\x13 \x01(\x02\x32>\n\rMesoDealiaser\x12-\n\x11\x44\x65\x61liasRadarFrame\x12\x0b.RadarFrame\x1a\x0b.RadarFrameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nr2_types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEVEL3EXTDATA']._serialized_start=52
  _globals['_LEVEL3EXTDATA']._serialized_end=144
  _globals['_RADARFRAME']._serialized_start=147
  _globals['_RADARFRAME']._serialized_end=580
  _globals['_MESODEALIASER']._serialized_start=582
  _globals['_MESODEALIASER']._serialized_end=644
# @@protoc_insertion_point(module_scope)
